Repository opencloud-eu/web, pull requests merged in 2025-07, with the labels that each got.

#878 Translation languages
  packages/design-system/l10n/translations.json
  packages/web-app-activities/l10n/translations.json
  packages/web-app-admin-settings/l10n/translations.json
  packages/web-app-app-store/l10n/translations.json
  packages/web-app-epub-reader/l10n/translations.json
  packages/web-app-external/l10n/translations.json
  packages/web-app-files/l10n/translations.json
  packages/web-app-ocm/l10n/translations.json
  packages/web-app-pdf-viewer/l10n/translations.json
  packages/web-app-preview/l10n/translations.json
  packages/web-app-search/l10n/translations.json
  packages/web-app-text-editor/l10n/translations.json
  packages/web-app-webfinger/l10n/translations.json
  packages/web-client/l10n/translations.json
  packages/web-pkg/l10n/translations.json
  packages/web-runtime/l10n/translations.json
  packages/web-runtime/src/defaults/languages.ts
  packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
Labels: Type:Maintenance

#875 chore: make use of resource-table in trashbin overview
  packages/web-app-files/src/views/trash/Overview.vue
  packages/web-app-files/tests/unit/views/trash/Overview.spec.ts
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-pkg/src/components/FilesList/ResourceIcon.vue
  packages/web-pkg/src/helpers/folderLink/types.ts
  tests/e2e/support/objects/app-files/trashbin/actions.ts
Labels: Type:Maintenance

#838 [full-ci] flush all the build cache
  .woodpecker.star
Labels: Type:Test

#886 enable a11y tests in CI
  .woodpecker.star
  tests/e2e/cucumber/features/a11y/smoke.feature
  tests/e2e/cucumber/steps/ui/a11.y.ts
  tests/e2e/support/utils/accessibility.ts
Labels: Type:Test

#908 fix(design-system): default colors for some of the icons
  packages/design-system/src/tokens/ods/color.yaml
Labels: Type:Bug

#912 feat: revert material design color hacks
  packages/design-system/src/components/OcTable/OcTable.vue
  packages/web-pkg/src/components/FilesList/ResourceTile.vue
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTile.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
  packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
  packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue
Labels: Type:Enhancement

#905 Improve Trashbin
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/RecipientContainer.vue
  packages/web-app-files/src/components/SideBar/TrashNoSelection.vue
  packages/web-app-files/src/components/Trash/TrashContextActions.vue
  packages/web-app-files/src/components/Trash/TrashQuickActions.vue
  packages/web-app-files/src/composables/extensions/useTrashActions.ts
  packages/web-app-files/src/extensionPoints.ts
  packages/web-app-files/src/extensions.ts
  packages/web-app-files/src/views/spaces/GenericTrash.vue
  packages/web-app-files/src/views/trash/Overview.vue
  packages/web-app-files/tests/unit/components/Trash/TrashContextActions.spec.ts
  packages/web-app-files/tests/unit/views/spaces/GenericTrash.spec.ts
  packages/web-app-files/tests/unit/views/trash/Overview.spec.ts
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-client/src/graph/drives/drives.ts
  packages/web-client/src/graph/drives/types.ts
  packages/web-client/src/graph/generated/.openapi-generator/VERSION
  packages/web-client/src/graph/generated/api.ts
  packages/web-client/src/graph/generated/common.ts
  packages/web-client/src/helpers/space/functions.ts
  packages/web-client/src/helpers/space/types.ts
  packages/web-pkg/src/components/AppBar/AppBar.vue
  packages/web-pkg/src/components/FilesList/ContextActions.vue
  packages/web-pkg/src/components/FilesList/ResourceStatusIndicators.vue
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/src/components/ViewOptions.vue
  packages/web-pkg/src/composables/actions/files/useFileActionsEmptyTrashBin.ts
  packages/web-pkg/src/composables/actions/spaces/useSpaceActionsNavigateToTrash.ts
  packages/web-pkg/src/composables/piniaStores/resources.ts
  packages/web-pkg/tests/unit/components/FilesList/ResourceTable.spec.ts
  packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActionsEmptyTrashBin.spec.ts
  packages/web-runtime/src/container/bootstrap.ts
Labels: Type:Enhancement

#916 e2e tests. set space image using context menu
  tests/e2e/cucumber/features/spaces/project.feature
  tests/e2e/cucumber/steps/ui/spaces.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
  tests/e2e/support/objects/app-files/spaces/index.ts
Labels: Type:Test

#933 [full-ci] bump-opencloud-2.0.3
  .woodpecker.env
Labels: Type:Dependencies

#945 chore(ci): use corepack for translation sync
  .woodpecker.star
Labels: Type:Bug

#950 test: get rid of unit test warnings [Vue warn]: Component is missing …
  packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
  packages/web-app-epub-reader/tests/unit/__snapshots__/app.spec.ts.snap
  packages/web-app-files/tests/unit/components/AppBar/Upload/__snapshots__/ResourceUpload.spec.ts.snap
  packages/web-app-files/tests/unit/components/Shares/__snapshots__/CopyPrivateLink.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/CopyLink.spec.ts.snap
  packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-pkg/tests/unit/components/AppBar/__snapshots__/CreateSpace.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ActionMenuDropItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextActionMenu.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextMenuQuickAction.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
  packages/web-pkg/tests/unit/components/Filters/__snapshots__/DateFilter.spec.ts.snap
  packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/SidebarToggle.spec.ts.snap
  packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
  tests/unit/config/vitest.config.ts
  tests/unit/stubs/vue-inline-svg.ts
Labels: Type:Bug, Type:Test

#953 e2e test. Empty trashbin using quick action
  .woodpecker.env
  tests/e2e/cucumber/features/smoke/trashbinDelete.feature
  tests/e2e/cucumber/steps/ui/trashbin.ts
  tests/e2e/support/objects/app-files/trashbin/actions.ts
  tests/e2e/support/objects/app-files/trashbin/index.ts
Labels: Type:Test

#931 alwaysUseVips
  .woodpecker.env
  .woodpecker.star
Labels: Type:DevOps

#976 fix: markdown editor, adjust word break
  packages/web-pkg/src/components/TextEditor/TextEditor.vue
Labels: Type:Bug

#980 feat: make web installable as PWA
  packages/web-container/img/opencloud-icon-lilac.svg
  packages/web-container/img/opencloud-icon.png
  packages/web-container/manifest.json
Labels: Type:Enhancement

#982 e2e-tests. clear input before fill name
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: Type:Test

#960 [full-ci] add pipeline to send CI notifications to matrix-channel
  .woodpecker.star
Labels: Type:Test

#954 cross browser testing
  .woodpecker.star
  cucumber.mjs
  package.json
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/cucumber/features/smoke/sse.feature
  tests/e2e/cucumber/features/smoke/upload.feature
  tests/e2e/filesForUpload/FOLDER/.gitkeep
  tests/e2e/run-e2e.sh
  tests/e2e/support/environment/actor/actor.ts
  tests/e2e/support/environment/actor/shared.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/utils/dragDrop.ts
Labels: Type:Test

#1013 e2e-test. fix share with multiple user test
  tests/e2e/support/objects/app-files/share/collaborator.ts
Labels: Type:Test

#1010 fix flaky close viewer after download
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/utils/editor.ts
Labels: Type:Test

#993 chore(deps): bump pbkdf2 to 3.1.3 to fix CVE
  pnpm-lock.yaml
Labels: Type:Dependencies
