Repository opencloud-eu/web, pull requests merged in 2025-05, with the labels that each got.

#622 fix:open in app action is available inside an app
  packages/web-pkg/src/composables/actions/files/useFileActions.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActions.spec.ts
Labels: Type:Bug

#623 fix: space description has a grey background
  packages/web-app-files/src/components/Spaces/SpaceHeader.vue
  packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
  packages/web-pkg/src/components/TextEditor/TextEditor.vue
Labels: Type:Bug

#616 feat: delete file from within preview app
  packages/web-app-preview/src/App.vue
  packages/web-app-preview/src/components/MediaControls.vue
  packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
  packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue
  packages/web-pkg/src/composables/actions/files/useFileActionsCopy.ts
  packages/web-pkg/src/composables/actions/files/useFileActionsMove.ts
  packages/web-pkg/src/composables/actions/files/useFileActionsPaste.ts
  packages/web-pkg/src/composables/keyboardActions/useKeyboardActions.ts
  packages/web-pkg/src/helpers/index.ts
  packages/web-pkg/src/helpers/platform.ts
  tests/e2e/cucumber/features/file-action/delete.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: Type:Enhancement

#621 fix: embed mode allows to choose locations that are not accessible
  packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
  packages/web-app-files/tests/unit/components/EmbedActions/EmbedActions.spec.ts
Labels: Type:Bug

#633 fix: preview user cannot delete file in the shared with me page
  packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
Labels: Type:Bug

#630 fix: delete button in preview app media controls visible, even if permissions missions aren't granted
  packages/web-app-preview/src/App.vue
  packages/web-app-preview/src/components/MediaControls.vue
Labels: Type:Bug

#639 fix: opening previews in share spaces
  packages/web-app-preview/src/App.vue
Labels: Type:Bug

#640 fix: preview user cannot delete file in the shared with me page (followup)
  packages/web-app-preview/src/App.vue
  packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
Labels: Type:Bug

#642 fix: chrome oh snap errors
  packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue
  packages/web-app-files/tests/unit/components/SideBar/ActivitiesPanel.spec.ts
  packages/web-pkg/src/components/SideBar/SideBar.vue
Labels: Type:Bug

#645 fix: add fallback font
  packages/design-system/docs/.vitepress/theme/custom.scss
  packages/design-system/src/assets/fonts/inter.css
  packages/design-system/src/assets/fonts/inter.woff2
  packages/design-system/src/tokens/ods/font.yaml
  packages/design-system/src/utils/webFontLoader.ts
Labels: Type:Bug

#649 upload folder via dragAndDrop
  tests/e2e/cucumber/features/smoke/upload.feature
  tests/e2e/support/utils/dragDrop.ts
Labels: Type:Test

#647 fix: bring back the left top rounded corner in the app bar
  packages/web-pkg/src/components/AppBar/AppBar.vue
Labels: Type:Bug

#651 fix: bring back the left top rounded corner in the app bar
  packages/web-pkg/src/components/AppBar/AppBar.vue
Labels: Type:Bug

#655 chore(design-system): remove webfontloader
  packages/design-system/package.json
  packages/design-system/src/assets/fonts/inter.css
  packages/design-system/src/assets/fonts/opencloud.css
  packages/design-system/src/index.ts
  packages/design-system/src/styles/fonts.scss
  packages/design-system/src/utils/webFontLoader.ts
  packages/design-system/vite.config.ts
  pnpm-lock.yaml
  tests/unit/config/vitest.config.ts
  tests/unit/stubs/webfontloader.ts
Labels: Type:Maintenance

#654 feat(design-system): make component types available for lib usage
  packages/design-system/README.md
  packages/design-system/package.json
  packages/design-system/vite.config.ts
Labels: Type:Enhancement

#658 Asset bundling
  packages/design-system/vite.config.ts
  vite.config.ts
Labels: Type:Maintenance

#660 Update languages in the web ui and patch translations
  packages/design-system/l10n/translations.json
  packages/web-app-activities/l10n/translations.json
  packages/web-app-admin-settings/l10n/translations.json
  packages/web-app-app-store/l10n/translations.json
  packages/web-app-epub-reader/l10n/translations.json
  packages/web-app-external/l10n/translations.json
  packages/web-app-files/l10n/translations.json
  packages/web-app-ocm/l10n/translations.json
  packages/web-app-pdf-viewer/l10n/translations.json
  packages/web-app-preview/l10n/translations.json
  packages/web-app-search/l10n/translations.json
  packages/web-app-text-editor/l10n/translations.json
  packages/web-app-webfinger/l10n/translations.json
  packages/web-client/l10n/translations.json
  packages/web-pkg/l10n/translations.json
  packages/web-runtime/l10n/translations.json
  packages/web-runtime/src/defaults/languages.ts
Labels: Type:Maintenance

#664 feat(design-system): add option for icon url prefix
  packages/design-system/src/components/OcIcon/OcIcon.vue
  packages/design-system/src/helpers/icons.ts
  packages/design-system/src/helpers/index.ts
  packages/design-system/src/index.ts
  packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
Labels: Type:Enhancement

#665 docs(design-system): type install options
  packages/design-system/README.md
  packages/design-system/src/helpers/index.ts
  packages/design-system/src/helpers/installOptions.ts
  packages/design-system/src/index.ts
Labels: Type:Documentation

#667 fix: add missing icon for otp
  packages/web-pkg/src/helpers/resource/icon.ts
Labels: Type:Bug

#669 fix(design-system): adjust primary and onPrimary color roles
  packages/design-system/src/tokens/ods/role.yaml
Labels: Type:Bug

#670 [stable-2.1] fix: add missing icon for otp
  packages/web-pkg/src/helpers/resource/icon.ts
Labels: Type:Bug

#671 chore: add .backportrc.json
  .backportrc.json
Labels: Type:Maintenance

#673 chore(design-system): add missing portal-vue dependency
  packages/design-system/package.json
  packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
  packages/design-system/src/components/OcTextInput/OcTextInput.vue
  packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
  packages/web-runtime/package.json
  pnpm-lock.yaml
Labels: Type:Maintenance

#677 chore: bump collabora to v25
  docker-compose.yml
Labels: Type:Maintenance

#675 feat(design-system): add required mark to text input component
  packages/design-system/src/components/OcDatepicker/__snapshots__/OcDatepicker.spec.ts.snap
  packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
  packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
  packages/design-system/src/components/OcTextInput/OcTextInput.vue
  packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
  packages/design-system/src/styles/theme/oc-text.scss
  packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/__snapshots__/MembersPanel.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/__snapshots__/MembersPanel.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-pkg/tests/unit/components/Filters/__snapshots__/DateFilter.spec.ts.snap
  packages/web-runtime/tests/unit/pages/__snapshots__/resolvePublicLink.spec.ts.snap
Labels: Type:Feature

#678 feat(design-system): add file input component
  packages/design-system/docs/.vitepress/config.ts
  packages/design-system/docs/components/OcFileInput/OcFileInput.md
  packages/design-system/docs/components/OcFileInput/default.vue
  packages/design-system/src/components/OcFileInput/OcFileInput.spec.ts
  packages/design-system/src/components/OcFileInput/OcFileInput.vue
  packages/design-system/src/components/index.ts
Labels: Type:Enhancement

#682 fix(design-system): filled a button hover
  packages/design-system/src/components/OcButton/OcButton.vue
Labels: Type:Bug

#684 feat(design-system): add OcColorInput component
  packages/design-system/docs/.vitepress/config.ts
  packages/design-system/docs/components/OcColorInput/OcColorInput.md
  packages/design-system/docs/components/OcColorInput/default.vue
  packages/design-system/src/components/OcColorInput/OcColorInput.spec.ts
  packages/design-system/src/components/OcColorInput/OcColorInput.vue
  packages/design-system/src/components/index.ts
Labels: Type:Enhancement

#685 chore(design-system): prepare 2.4.0-alpha.1 release
  packages/design-system/package.json
Labels: Type:Maintenance

#686 fix: minor design system issues and styling
  packages/design-system/src/components/OcColorInput/OcColorInput.vue
  packages/design-system/src/components/OcDatepicker/__snapshots__/OcDatepicker.spec.ts.snap
  packages/design-system/src/components/OcFileInput/OcFileInput.vue
  packages/design-system/src/components/OcSelect/OcSelect.vue
  packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
  packages/design-system/src/components/OcTextInput/OcTextInput.vue
  packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
  packages/design-system/src/styles/theme/oc-text.scss
  packages/design-system/types.d.ts
  packages/web-pkg/tests/unit/components/Filters/__snapshots__/DateFilter.spec.ts.snap
  tests/e2e/support/objects/app-files/link/actions.ts
Labels: Type:Bug

#690 chore(design-system): prepare 2.4.0-alpha.2 release
  packages/design-system/package.json
Labels: Type:Maintenance

#618 Added better shift-click handling for files and folders
  packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
  packages/web-app-files/src/components/Search/List.vue
  packages/web-app-files/src/composables/keyboardActions/index.ts
  packages/web-app-files/src/composables/keyboardActions/useKeyboardFileActions.ts
  packages/web-app-files/src/composables/keyboardActions/useKeyboardFileMouseActions.ts
  packages/web-app-files/src/composables/keyboardActions/useKeyboardFileNavigation.ts
  packages/web-app-files/src/composables/keyboardActions/useKeyboardFileSpaceActions.ts
  packages/web-app-files/src/views/spaces/GenericSpace.vue
  packages/web-app-files/src/views/spaces/Projects.vue
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/src/components/FilesList/ResourceTiles.vue
Labels: Type:Bug

#691 fix(design-system): text input error message icon position
  packages/design-system/src/components/OcTextInput/OcTextInput.vue
Labels: Type:Bug

#711 chore: bump versions to 2.4.0
  package.json
  packages/design-system/package.json
  packages/eslint-config/package.json
  packages/extension-sdk/package.json
  packages/prettier-config/package.json
  packages/tsconfig/package.json
  packages/web-client/package.json
  packages/web-pkg/package.json
  packages/web-test-helpers/package.json
Labels: Type:Maintenance

#713 🎉 Release 2.4.0
  CHANGELOG.md
Labels: Type:Maintenance

#714 [full-ci] opencloud bump v 2.3.0. run all tests
  .woodpecker.env
Labels: Type:Dependencies

#721 feat: remove space membership info in file list
  packages/web-app-files/src/components/SideBar/Shares/FileShares.vue
  packages/web-app-files/src/views/spaces/Projects.vue
  packages/web-app-files/tests/unit/components/SideBar/Shares/FileShares.spec.ts
  packages/web-client/src/helpers/space/functions.ts
  packages/web-client/src/helpers/space/types.ts
  packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
  packages/web-pkg/src/composables/piniaStores/resources.ts
  packages/web-pkg/src/composables/spaces/useGetMatchingSpace.ts
  packages/web-pkg/src/helpers/statusIndicators.ts
  packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetails.spec.ts
  packages/web-pkg/tests/unit/helpers/statusIndicator.spec.ts
Labels: Type:Enhancement

#707 feat: polish account page design
  packages/web-runtime/src/components/Account/AccountTable.vue
  packages/web-runtime/src/components/Account/AppTokens.vue
  packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
Labels: Type:Feature

#724 chore(design-system): make translations usable in library mode
  packages/design-system/README.md
  packages/design-system/package.json
  packages/design-system/src/helpers/installOptions.ts
  packages/design-system/src/index.ts
  packages/design-system/vite.config.ts
Labels: Type:Maintenance

#726 chore(design-system): prepare 2.5.0-alpha.1 release
  packages/design-system/package.json
Labels: Type:Maintenance

#722 feat: add cropping to space images
  packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
  packages/web-app-files/src/components/Spaces/SpaceContextActions.vue
  packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
  packages/web-app-files/tests/unit/composables/actions/spaces/useSpaceActionsUploadImage.spec.ts
  packages/web-pkg/src/components/Spaces/SpaceImageModal.vue
  packages/web-pkg/src/components/Spaces/index.ts
  packages/web-pkg/src/composables/actions/files/useFileActionsSetImage.ts
  packages/web-pkg/tests/unit/components/Spaces/SpaceImageModal.spec.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActionsSetImage.spec.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
Labels: Type:Feature

#728 chore: save space emoji as image.png
  packages/web-pkg/src/composables/actions/spaces/useSpaceActionsSetIcon.ts
Labels: Type:Maintenance

#734 fix: SpaceImageModal import
  packages/web-pkg/src/composables/actions/files/useFileActionsSetImage.ts
Labels: Type:Bug

#693 feat: Added CalDAV URL to the Accountpage
  dev/docker/opencloud/proxy.yaml
  dev/docker/radicale/config
  docker-compose.yml
  packages/design-system/src/components/OcTag/OcTag.vue
  packages/design-system/src/components/OcTag/__snapshots__/OcTag.spec.ts.snap
  packages/web-runtime/src/components/Account/CalDavUrl.vue
  packages/web-runtime/src/extensions.ts
  packages/web-runtime/tests/unit/components/Account/CalDavUrl.spec.ts
Labels: Type:Feature

#738 feat: polish account page followup
  packages/web-runtime/src/components/Account/AppTokens.vue
Labels: Type:Enhancement

#741 chore: update translations
  packages/design-system/l10n/translations.json
  packages/web-app-activities/l10n/translations.json
  packages/web-app-admin-settings/l10n/translations.json
  packages/web-app-app-store/l10n/translations.json
  packages/web-app-epub-reader/l10n/translations.json
  packages/web-app-external/l10n/translations.json
  packages/web-app-files/l10n/translations.json
  packages/web-app-ocm/l10n/translations.json
  packages/web-app-pdf-viewer/l10n/translations.json
  packages/web-app-preview/l10n/translations.json
  packages/web-app-search/l10n/translations.json
  packages/web-app-text-editor/l10n/translations.json
  packages/web-app-webfinger/l10n/translations.json
  packages/web-client/l10n/translations.json
  packages/web-pkg/l10n/translations.json
  packages/web-runtime/l10n/translations.json
Labels: Type:Maintenance

#747 feat: extract first frame from gif, so space image cropping works fla…
  packages/web-pkg/src/components/Spaces/SpaceImageModal.vue
Labels: Type:Feature

#742 e2e tests. user profile photo
  .woodpecker.env
  tests/e2e/cucumber/features/user-settings/profilePhoto.feature
  tests/e2e/cucumber/steps/ui/accountMenu.ts
  tests/e2e/support/objects/account/actions.ts
  tests/e2e/support/objects/account/index.ts
Labels: Type:Test

#761 chore: adjust admin settings details panels
  packages/web-app-admin-settings/src/components/Groups/SideBar/DetailsPanel.vue
  packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
Labels: Type:Maintenance
