Repository opencloud-eu/web, pull requests merged in 2025-08, with the labels that each got.

#1033 feat: dispatch pathchange event for external integrations
  packages/web-runtime/src/router/setupRouter.ts
Labels: Type:Enhancement

#1051 fix: resource deselect when clicking esc in a modal
  packages/design-system/src/components/OcModal/OcModal.vue
Labels: Type:Bug

#1046 fix extension registry stable order
  dev/docker/opencloud/csp.yaml
  packages/web-pkg/src/components/SideBar/SideBar.vue
  packages/web-pkg/src/composables/actions/files/useFileActionsToggleHideShare.ts
  packages/web-runtime/src/container/application/index.ts
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/tests/unit/container/bootstrap.spec.ts
Labels: Type:Bug

#1018 feat: preserve empty folders on upload
  packages/web-app-files/src/HandleUpload.ts
  packages/web-app-files/src/components/AppBar/Upload/ResourceUpload.vue
  packages/web-app-files/src/helpers/directoryPicker.ts
  packages/web-app-files/tests/unit/HandleUpload.spec.ts
  packages/web-pkg/package.json
  packages/web-pkg/src/services/uppy/DropTarget/getDroppedFiles.ts
  packages/web-pkg/src/services/uppy/DropTarget/plugin.ts
  packages/web-pkg/src/services/uppy/DropTarget/types.ts
  packages/web-pkg/src/services/uppy/index.ts
  packages/web-pkg/src/services/uppy/uppyService.ts
  packages/web-pkg/src/services/uppy/utils.ts
  packages/web-pkg/tests/unit/services/uppy/DropTarget/getDroppedFiles.spec.ts
  packages/web-pkg/tests/unit/services/uppy/utils.spec.ts
  packages/web-runtime/package.json
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/tests/unit/components/UploadInfo.spec.ts
  pnpm-lock.yaml
Labels: Type:Enhancement

#1053 fix: crippled search after leaving public link
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
Labels: Type:Bug

#1058 fix: dynamic viewport height on mobile devices
  packages/web-runtime/src/App.vue
  packages/web-runtime/src/layouts/Application.vue
Labels: Type:Bug

#1062 feat(preview): add webp as supported mimetype
  packages/web-app-preview/src/mimeTypes.ts
  packages/web-pkg/src/helpers/resource/icon.ts
Labels: Type:Enhancement

#1057 enable upload tests for webkit
  package.json
  tests/e2e/cucumber/features/smoke/upload.feature
Labels: Type:Test

#1067 test: fix unit test warnings
  packages/web-app-search/tests/unit/portals/SearchBar.spec.ts
Labels: Type:Test

#1060 fix: incoming group share name in sidebar
  packages/web-pkg/src/components/SideBar/Files/FileInfo.vue
  packages/web-pkg/src/composables/spaces/useGetMatchingSpace.ts
Labels: Type:Bug

#979 🎉 Release 3.3.0
  CHANGELOG.md
Labels: Type:Documentation

#1074 [full-ci] bump-opencloud-3.3.0. run all tests
  .woodpecker.env
Labels: Type:Dependencies

#1081 refactor: rename defaultExtension to defaultAppId
  packages/web-pkg/src/composables/piniaStores/config/config.ts
  packages/web-pkg/src/composables/piniaStores/config/types.ts
  packages/web-runtime/src/container/bootstrap.ts
Labels: Type:Maintenance

#1101 fix: font-weight in contextual helpers
  packages/design-system/src/components/OcDefinitionList/OcDefinitionList.vue
  packages/design-system/src/components/OcInfoDrop/OcInfoDrop.vue
Labels: Type:Bug

#1107 refactor: move tailwind.css file to design-system
  packages/design-system/package.json
  packages/design-system/src/components/OcAvatars/OcAvatars.vue
  packages/design-system/src/components/OcBottomDrawer/OcBottomDrawer.vue
  packages/design-system/src/components/OcButton/OcButton.vue
  packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
  packages/design-system/src/components/OcDefinitionList/OcDefinitionList.vue
  packages/design-system/src/components/OcDropzone/OcDropzone.vue
  packages/design-system/src/components/OcIcon/OcIcon.vue
  packages/design-system/src/components/OcList/OcList.vue
  packages/design-system/src/components/OcLoader/OcLoader.vue
  packages/design-system/src/components/OcNotificationMessage/OcNotificationMessage.vue
  packages/design-system/src/components/OcNotifications/OcNotifications.vue
  packages/design-system/src/components/OcProgressPie/OcProgressPie.vue
  packages/design-system/src/components/OcRadio/OcRadio.vue
  packages/design-system/src/components/OcRecipient/OcRecipient.vue
  packages/design-system/src/components/OcSelect/OcSelect.vue
  packages/design-system/src/components/OcTableCell/OcTableCell.vue
  packages/design-system/src/components/OcTableTh/OcTableTh.vue
  packages/design-system/src/components/OcTag/OcTag.vue
  packages/design-system/src/styles/layers.css
  packages/design-system/src/styles/tailwind.css
  packages/design-system/vite.config.ts
  packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
  packages/web-app-admin-settings/src/components/Users/UsersList.vue
  packages/web-app-files/src/components/Search/List.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/InviteCollaborator/InviteCollaboratorForm.vue
  packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
  packages/web-app-search/src/portals/SearchBar.vue
  packages/web-pkg/src/components/BatchActions.vue
  packages/web-pkg/src/components/ContextActions/ContextActionMenu.vue
  packages/web-pkg/src/components/FilesList/ResourceTiles.vue
  packages/web-pkg/src/components/Filters/DateFilter.vue
  packages/web-pkg/src/components/Modals/FilePickerModal.vue
  packages/web-pkg/src/components/Modals/SaveAsModal.vue
  packages/web-pkg/src/components/SideBar/Files/FileInfo.vue
  packages/web-pkg/src/components/TextEditor/TextEditor.vue
  packages/web-runtime/src/App.vue
  packages/web-runtime/src/components/Account/AccountTable.vue
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/src/tailwind.css
  packages/web-runtime/src/tailwind.ts
  vite.config.ts
Labels: Type:Maintenance

#1105 chore: adjust flexbox css props to tailwind followup
  index.html
  packages/design-system/src/components/OcAvatar/OcAvatar.vue
  packages/design-system/src/components/OcAvatarCount/OcAvatarCount.vue
  packages/design-system/src/components/OcAvatarCount/__snapshots__/OcAvatarCount.spec.ts.snap
  packages/design-system/src/components/OcColorInput/OcColorInput.vue
  packages/design-system/src/components/OcDatepicker/__snapshots__/OcDatepicker.spec.ts.snap
  packages/design-system/src/components/OcDefinitionList/OcDefinitionList.vue
  packages/design-system/src/components/OcDropzone/OcDropzone.vue
  packages/design-system/src/components/OcFileInput/OcFileInput.vue
  packages/design-system/src/components/OcList/OcList.vue
  packages/design-system/src/components/OcModal/OcModal.vue
  packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
  packages/design-system/src/components/OcPageSize/OcPageSize.vue
  packages/design-system/src/components/OcPagination/OcPagination.vue
  packages/design-system/src/components/OcRecipient/OcRecipient.vue
  packages/design-system/src/components/OcTable/OcTable.vue
  packages/design-system/src/components/OcTextInput/OcTextInput.vue
  packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
  packages/design-system/src/components/OcTextInputPassword/OcTextInputPassword.vue
  packages/design-system/src/components/OcTextarea/OcTextarea.vue
  packages/web-app-admin-settings/src/components/AppTemplate.vue
  packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/__snapshots__/EditPanel.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
  packages/web-app-app-store/src/components/AppActions.vue
  packages/web-app-app-store/src/components/AppImageGallery.vue
  packages/web-app-app-store/src/components/AppTags.vue
  packages/web-app-app-store/src/components/AppTile.vue
  packages/web-app-app-store/src/views/AppDetails.vue
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/__snapshots__/RecipientContainer.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/__snapshots__/ActivitiesPanel.spec.ts.snap
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-app-preview/src/App.vue
  packages/web-pkg/src/components/AppBar/AppBar.vue
  packages/web-pkg/src/components/FilesList/ResourceListItem.vue
  packages/web-pkg/src/components/FilesList/ResourceName.vue
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/src/components/FilesList/ResourceTile.vue
  packages/web-pkg/src/components/FilesList/ResourceTiles.vue
  packages/web-pkg/src/components/SideBar/SideBar.vue
  packages/web-pkg/src/components/ViewOptions.vue
  packages/web-pkg/tests/unit/components/AppBar/__snapshots__/AppBar.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceName.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTile.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
  packages/web-pkg/tests/unit/components/Filters/__snapshots__/DateFilter.spec.ts.snap
  packages/web-runtime/src/components/Modals/AppTokenModal.vue
  packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
  packages/web-runtime/src/components/SidebarNav/SidebarNavItem.vue
  packages/web-runtime/src/components/Topbar/TopBar.vue
  packages/web-runtime/src/components/Topbar/UserMenu.vue
  packages/web-runtime/src/layouts/Application.vue
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNavItem.spec.ts.snap
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap
  packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
Labels: Type:Maintenance

#1108 run design-system-docs pipeline on cron
  .woodpecker.star
Labels: Type:DevOps
