Repository opencloud-eu/web, pull requests merged in 2025-03, with the labels that each got.

#336 Update translations
  packages/design-system/l10n/translations.json
  packages/web-app-activities/l10n/translations.json
  packages/web-app-admin-settings/l10n/translations.json
  packages/web-app-app-store/l10n/translations.json
  packages/web-app-epub-reader/l10n/translations.json
  packages/web-app-external/l10n/translations.json
  packages/web-app-files/l10n/translations.json
  packages/web-app-ocm/l10n/translations.json
  packages/web-app-pdf-viewer/l10n/translations.json
  packages/web-app-preview/l10n/translations.json
  packages/web-app-search/l10n/translations.json
  packages/web-app-text-editor/l10n/translations.json
  packages/web-app-webfinger/l10n/translations.json
  packages/web-client/l10n/translations.json
  packages/web-pkg/l10n/translations.json
  packages/web-runtime/l10n/translations.json
Labels: Type:Maintenance

#340 Bump version to v2.0.0
  package.json
  packages/design-system/package.json
  packages/design-system/src/tokens/ods/role.yaml
  packages/eslint-config/package.json
  packages/extension-sdk/package.json
  packages/prettier-config/package.json
  packages/tsconfig/package.json
  packages/web-client/package.json
  packages/web-pkg/package.json
  packages/web-test-helpers/package.json
  sonar-project.properties
Labels: Type:Organizational

#347 chore(prettier-config): make prettier a peer dependency
  packages/prettier-config/package.json
Labels: Type:Maintenance

#358 fix(files): deletion date in file details
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
Labels: Type:Bug

#368 fix(files): outline on space member filter input
  packages/web-app-files/src/components/SideBar/Shares/SpaceMembers.vue
  packages/web-app-files/tests/unit/components/SideBar/Shares/SpaceMembers.spec.ts
Labels: Type:Bug

#377 fix(design-system): jumpyness when focusing password input
  packages/design-system/src/components/OcTextInputPassword/OcTextInputPassword.vue
Labels: Type:Bug

#378 delete unused uuids after fix #364
  tests/e2e/support/objects/app-admin-settings/users/actions.ts
  tests/e2e/support/objects/app-admin-settings/users/index.ts
Labels: Type:Test

#379 fix(pkg): pixelated previews after searching
  packages/web-pkg/src/components/Search/ResourcePreview.vue
  packages/web-pkg/tests/unit/components/Search/ResourcePreview.spec.ts
Labels: Type:Bug

#383 fix(admin-settings): outline on space member filter input
  packages/web-app-admin-settings/src/components/Spaces/SideBar/MembersPanel.vue
  packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/MembersPanel.spec.ts
  packages/web-app-admin-settings/tests/unit/components/Spaces/SideBar/__snapshots__/MembersPanel.spec.ts.snap
Labels: Type:Bug

#384 fix: table header overflows content
  packages/design-system/src/components/OcTable/OcTable.vue
  packages/web-app-admin-settings/src/components/AppTemplate.vue
  packages/web-pkg/src/components/AppBar/AppBar.vue
Labels: Type:Bug

#363 fix: select all checkbox in spaces tiles view
  packages/web-pkg/src/components/FilesList/ResourceTiles.vue
  packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
Labels: Type:Bug

#385 feat: adjust avatar color in user menu
  packages/web-runtime/src/components/Topbar/UserMenu.vue
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/UserMenu.spec.ts.snap
Labels: Type:Design

#381 fix(files): copy pasting items into current folder
  packages/design-system/src/components/OcButton/OcButton.vue
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/tests/unit/components/AppBar/CreateAndUpload.spec.ts
Labels: Type:Bug

#389 fix(pkg): add missing delete queue to tiles view
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/src/components/FilesList/ResourceTile.vue
  packages/web-pkg/src/components/FilesList/ResourceTiles.vue
  packages/web-pkg/tests/unit/components/FilesList/ResourceTile.spec.ts
  packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
Labels: Type:Bug

#390 fix(pkg): space quota background color
  packages/design-system/src/components/OcProgress/OcProgress.vue
  packages/design-system/src/components/OcProgress/__snapshots__/OcProgress.spec.ts.snap
  packages/web-pkg/src/components/SpaceQuota.vue
  packages/web-pkg/tests/unit/components/__snapshots__/SpaceQuota.spec.ts.snap
Labels: Type:Bug

#395 fix: various hovers and small visual glitches
  packages/design-system/src/components/OcStatusIndicators/OcStatusIndicators.vue
  packages/design-system/src/components/OcTable/OcTable.vue
  packages/web-app-admin-settings/src/views/Spaces.vue
  packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
  packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
  packages/web-app-files/src/views/trash/Overview.vue
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-pkg/src/components/FilesList/ResourceLink.vue
  packages/web-pkg/src/components/FilesList/ResourceListItem.vue
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/src/components/LinkRoleDropdown.vue
  packages/web-pkg/src/components/ViewOptions.vue
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
  packages/web-runtime/src/components/Topbar/Notifications.vue
  packages/web-runtime/src/pages/accessDenied.vue
  packages/web-runtime/tests/unit/pages/__snapshots__/accessDenied.spec.ts.snap
Labels: Type:Bug

#396 check formatting in CI
  .prettierignore
  .woodpecker.star
  packages/design-system/docs/components/OcList/OcList.md
  release-config.ts
  tests/e2e/support/objects/app-admin-settings/users/actions.ts
  tests/e2e/support/objects/app-files/spaces/actions.ts
  tests/e2e/support/objects/app-files/spaces/index.ts
Labels: Type:DevOps

#398 feat: space image loading indicator
  packages/web-app-admin-settings/src/views/Spaces.vue
  packages/web-app-files/src/components/Spaces/SpaceHeader.vue
  packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
  packages/web-app-files/src/views/spaces/Projects.vue
  packages/web-app-files/tests/unit/components/Spaces/SpaceHeader.spec.ts
  packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
  packages/web-pkg/src/components/AppBar/AppBar.vue
  packages/web-pkg/src/components/AppBar/CreateSpace.vue
  packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
  packages/web-pkg/src/composables/piniaStores/spaces.ts
  packages/web-pkg/src/composables/resources/useLoadPreview.ts
  packages/web-pkg/tests/unit/components/sidebar/Spaces/Details/SpaceDetails.spec.ts
  packages/web-pkg/tests/unit/composables/resources/useLoadPreview.spec.ts
Labels: Type:Enhancement

#408 feat: space readme loading indicator
  packages/web-app-files/src/components/Spaces/SpaceHeader.vue
  packages/web-app-files/tests/unit/components/Spaces/SpaceHeader.spec.ts
  packages/web-pkg/src/composables/piniaStores/spaces.ts
  packages/web-test-helpers/src/mocks/pinia.ts
Labels: Type:Enhancement

#414 delete last (skipped) call to changelog function
  .woodpecker.star
Labels: Type:DevOps

#425 fix(design-system): align disabled select appearance with other inputs
  packages/design-system/src/components/OcSelect/OcSelect.vue
Labels: Type:Bug

#419 [full-ci] enable app-provider tests
  .woodpecker.star
  tests/e2e/support/api/external/openWithWeb.ts
Labels: Type:Test

#433 Enable ready release go and use v prefix for tags
  .woodpecker.star
  release-config.ts
Labels: Type:Maintenance

#434 fix: starlark fix
  .woodpecker.star
  release-config.ts
Labels: Type:DevOps

#432 feat(admin-settings): remove appearance section from General page
  .github/PULL_REQUEST_TEMPLATE.md
  packages/web-app-admin-settings/src/components/General/AppearanceSection.vue
  packages/web-app-admin-settings/src/composables/actions/general/index.ts
  packages/web-app-admin-settings/src/composables/actions/general/useGeneralActionsResetLogo.ts
  packages/web-app-admin-settings/src/composables/actions/general/useGeneralActionsUploadLogo.ts
  packages/web-app-admin-settings/src/composables/actions/index.ts
  packages/web-app-admin-settings/src/views/General.vue
  packages/web-app-admin-settings/tests/unit/composables/actions/general/useGeneralActionsResetLogo.spec.ts
  packages/web-app-admin-settings/tests/unit/composables/actions/general/useGeneralActionsUploadLogo.spec.ts
  tests/e2e/cucumber/features/admin-settings/general.feature
Labels: Type:Enhancement

#435 chore: bump versions to 2.1.0
  package.json
  packages/design-system/package.json
  packages/eslint-config/package.json
  packages/extension-sdk/package.json
  packages/prettier-config/package.json
  packages/tsconfig/package.json
  packages/web-client/package.json
  packages/web-pkg/package.json
  packages/web-test-helpers/package.json
  sonar-project.properties
Labels: Type:Maintenance

#343 🎉 Release 2.1.0
  CHANGELOG.md
Labels: Type:Maintenance

#412 Setup keycloak service for e2e tests in CI
  .woodpecker.star
  tests/e2e/support/api/keycloak/user.ts
  tests/e2e/support/environment/userManagement.ts
  tests/woodpecker/opencloud_keycloak/opencloud-ci-realm.dist.json
Labels: Type:DevOps

#443 Don't show backend edition when not set
  packages/web-app-admin-settings/src/components/General/InfoSection.vue
  packages/web-runtime/src/container/versions.ts
  packages/web-runtime/tests/unit/container/versions.spec.ts
Labels: Type:Bug

#445 chore: switch to daily backend image for dev stack
  docker-compose.yml
Labels: Type:Maintenance

#455 feat: change plain view button color
  packages/design-system/src/components/OcButton/OcButton.vue
  packages/web-runtime/src/pages/accessDenied.vue
  packages/web-runtime/src/pages/logout.vue
  packages/web-runtime/tests/unit/pages/__snapshots__/accessDenied.spec.ts.snap
Labels: Type:Design, Type:Enhancement
