Repository opencloud-eu/web, pull requests merged in 2025-06, with the labels that each got.

#774 fix(admin-settings): broken update user space quota for users with sp…
  packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
  packages/web-client/src/graph/drives/types.ts
Labels: Type:Bug

#767 feat: show avatars in shares view
  packages/design-system/src/components/OcAvatars/OcAvatars.spec.ts
  packages/design-system/src/components/OcAvatars/OcAvatars.vue
  packages/design-system/src/components/OcAvatars/__snapshots__/OcAvatars.spec.ts.snap
  packages/design-system/src/components/OcRecipient/OcRecipient.vue
  packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/__snapshots__/RecipientContainer.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/__snapshots__/ActivitiesPanel.spec.ts.snap
  packages/web-pkg/src/components/Avatars/UserAvatar.vue
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/src/composables/avatars/index.ts
  packages/web-pkg/src/composables/avatars/useLoadAvatars.ts
  packages/web-pkg/src/composables/index.ts
  packages/web-pkg/src/composables/piniaStores/avatars.ts
  packages/web-pkg/src/composables/piniaStores/config/config.ts
  packages/web-pkg/src/composables/piniaStores/config/types.ts
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/index.ts
  packages/web-runtime/src/services/auth/authService.ts
Labels: Type:Enhancement

#782 chore: bump version to v3.0.0-alpha.1
  package.json
  packages/design-system/package.json
  packages/eslint-config/package.json
  packages/extension-sdk/package.json
  packages/prettier-config/package.json
  packages/tsconfig/package.json
  packages/web-client/package.json
  packages/web-pkg/package.json
  packages/web-test-helpers/package.json
Labels: Type:Maintenance

#718 🎉 Release 3.0.0-alpha.1
  CHANGELOG.md
Labels: Type:Maintenance

#783 fix: modal window doesn't close on browser navigation
  packages/web-runtime/src/pages/logout.vue
  packages/web-runtime/src/router/index.ts
  packages/web-runtime/src/router/setupRouter.ts
Labels: Type:Bug

#792 e2e-tests. Check avatar tests in shares view
  tests/e2e/cucumber/features/user-settings/profilePhoto.feature
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/cucumber/steps/ui/notifications.ts
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/cucumber/steps/ui/shares.ts
  tests/e2e/filesForUpload/user-avatar.png
  tests/e2e/support/api/graph/index.ts
  tests/e2e/support/api/graph/userManagement.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
  tests/e2e/support/objects/app-files/share/collaborator.ts
  tests/e2e/support/objects/runtime/application.ts
Labels: Type:Test

#805 feat: add keyboard support for space image and user avatar cropping
  packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
  packages/web-pkg/src/components/Avatars/AvatarUpload.vue
  packages/web-pkg/src/components/Spaces/SpaceImageModal.vue
  packages/web-pkg/src/composables/keyboardActions/index.ts
  packages/web-pkg/src/composables/keyboardActions/useCropperKeyboardActions.ts
  packages/web-pkg/src/composables/keyboardActions/useKeyboardActions.ts
Labels: Type:Enhancement

#806 fix: status column appears multiple times
  packages/web-app-files/src/views/spaces/Projects.vue
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/src/helpers/statusIndicators.ts
Labels: Type:Bug

#810 Revert "fix(deps): update dependency eslint-plugin-n to v17.19.0"
  pnpm-lock.yaml
Labels: Type:Dependencies

#785 🎉 Release 3.0.0
  CHANGELOG.md
Labels: Type:Documentation

#812 fix: space member count in space header component
  packages/web-app-files/src/components/Spaces/SpaceHeader.vue
  packages/web-app-files/tests/unit/components/Spaces/SpaceHeader.spec.ts
  packages/web-client/src/graph/generated/api.ts
  packages/web-client/src/graph/generated/base.ts
  packages/web-client/src/graph/generated/common.ts
  packages/web-client/src/graph/generated/configuration.ts
  packages/web-client/src/graph/generated/index.ts
  packages/web-client/src/graph/permissions/permissions.ts
  packages/web-client/src/graph/permissions/types.ts
Labels: Type:Bug

#814 [full-ci]bump-opencloud-3.0.0
  .woodpecker.env
Labels: Type:Dependencies

#826 test: add unit tests for context menu drop
  packages/design-system/src/components/OcDrop/OcDrop.spec.ts
  packages/design-system/src/components/OcDrop/OcDrop.vue
  packages/web-pkg/src/components/ContextActions/ActionMenuDropItem.vue
  packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue
  packages/web-pkg/src/components/ContextActions/ContextActionMenu.vue
  packages/web-pkg/src/components/ContextActions/ContextMenuQuickAction.vue
  packages/web-pkg/src/components/FilesList/ContextActions.vue
  packages/web-pkg/src/composables/actions/files/useFileActionsNavigate.ts
  packages/web-pkg/tests/unit/components/ContextActions/ActionMenuDropItem.spec.ts
  packages/web-pkg/tests/unit/components/ContextActions/ContextActionMenu.spec.ts
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ActionMenuDropItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextActionMenu.spec.ts.snap
Labels: Type:Test

#828 fix: tiles view accidentatly show space status indicators
  packages/web-pkg/src/helpers/statusIndicators.ts
Labels: Type:Bug

#819 A11y tests
  package.json
  pnpm-lock.yaml
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/cucumber/environment/world.ts
  tests/e2e/cucumber/features/a11y/smoke.feature
  tests/e2e/cucumber/steps/ui/a11.y.ts
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/cucumber/steps/ui/session.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
  tests/e2e/support/objects/runtime/session.ts
  tests/e2e/support/utils/accessibility.ts
Labels: Type:Test

#834 delete logo steps
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/support/objects/app-admin-settings/general/actions.ts
  tests/e2e/support/objects/app-admin-settings/general/index.ts
  tests/e2e/support/objects/app-admin-settings/index.ts
Labels: Type:Test

#840 [full-ci] detect and delete unused steps
  package.json
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/cucumber/steps/ui/links.ts
  tests/e2e/cucumber/steps/ui/public.ts
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/cucumber/steps/ui/session.ts
  tests/e2e/cucumber/steps/ui/shares.ts
  tests/e2e/support/objects/app-files/link/actions.ts
  tests/e2e/support/objects/app-files/link/index.ts
  tests/e2e/support/objects/app-files/page/public.ts
  tests/e2e/support/objects/app-files/page/shares/withMe.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
  tests/e2e/support/objects/app-files/share/index.ts
  tests/e2e/support/objects/app-files/share/utils.ts
Labels: Type:Test

#849 feat: brand color default space image
  packages/design-system/src/assets/images/default-space-icon.png
Labels: Type:Enhancement

#827 get hostname of S3 server from var. not secret
  .woodpecker.star
Labels: Type:DevOps

#829 feat: add context menu action to remove space image
  packages/web-app-files/src/components/SideBar/Actions/SpaceActions.vue
  packages/web-app-files/src/components/Spaces/SpaceContextActions.vue
  packages/web-app-files/src/components/Spaces/SpaceHeader.vue
  packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
  packages/web-app-files/tests/unit/components/Spaces/SpaceHeader.spec.ts
  packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
  packages/web-pkg/src/components/Avatars/AvatarUpload.vue
  packages/web-pkg/src/components/ContextActions/ActionMenuDropItem.vue
  packages/web-pkg/src/components/ContextActions/ContextActionMenu.vue
  packages/web-pkg/src/components/FilesList/ContextActions.vue
  packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
  packages/web-pkg/src/components/Spaces/SpaceImageModal.vue
  packages/web-pkg/src/composables/actions/files/useFileActions.ts
  packages/web-pkg/src/composables/actions/spaces/index.ts
  packages/web-pkg/src/composables/actions/spaces/useSpaceActionsDeleteImage.ts
  packages/web-pkg/tests/unit/components/ContextActions/ActionMenuDropItem.spec.ts
  packages/web-pkg/tests/unit/components/ContextActions/ContextActionMenu.spec.ts
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextActionMenu.spec.ts.snap
  packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsDeleteImage.spec.ts
Labels: Type:Enhancement

#796 [with-tracing] Upload tracing results of UI tests to public S3
  .woodpecker.star
  tests/e2e/cucumber/environment/index.ts
Labels: Type:DevOps

#866 fix: upload space image broken
  packages/web-app-files/src/composables/actions/spaces/useSpaceActionsUploadImage.ts
Labels: Type:Bug

#873 chore: bump version to v3.1.0 for the upcoming rolling release
  package.json
  packages/design-system/package.json
  packages/eslint-config/package.json
  packages/extension-sdk/package.json
  packages/prettier-config/package.json
  packages/tsconfig/package.json
  packages/web-client/package.json
  packages/web-pkg/package.json
  packages/web-test-helpers/package.json
Labels: Type:Maintenance

#876 feat: improve visual representation on file name input errors
  packages/design-system/src/components/OcDatepicker/__snapshots__/OcDatepicker.spec.ts.snap
  packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
  packages/design-system/src/components/OcTextInput/OcTextInput.spec.ts
  packages/design-system/src/components/OcTextInput/OcTextInput.vue
  packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
  packages/web-app-admin-settings/src/components/Users/CreateUserModal.vue
  packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
  packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/__snapshots__/MembersPanel.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/components/Users/SideBar/__snapshots__/EditPanel.spec.ts.snap
  packages/web-app-files/tests/unit/composables/actions/spaces/useSpaceActionsUploadImage.spec.ts
  packages/web-pkg/src/components/AppBar/CreateSpace.vue
  packages/web-pkg/src/composables/actions/files/useFileActionsCreateSpaceFromResource.ts
  packages/web-pkg/src/composables/actions/helpers/useIsResourceNameValid.ts
  packages/web-pkg/src/composables/actions/spaces/useSpaceActionsRename.ts
  packages/web-pkg/src/composables/spaces/useSpaceHelpers.ts
  packages/web-pkg/tests/unit/components/Filters/__snapshots__/DateFilter.spec.ts.snap
  packages/web-pkg/tests/unit/components/Spaces/SpaceImageModal.spec.ts
  packages/web-pkg/tests/unit/composables/actions/files/useFileActionsSetImage.spec.ts
  packages/web-pkg/tests/unit/composables/actions/helpers/useIsResourceNameValid.spec.ts
  packages/web-pkg/tests/unit/composables/actions/spaces/useSpaceActionsEditReadmeContent.spec.ts
  packages/web-pkg/tests/unit/composables/spaces/useSpaceHelpers.spec.ts
  packages/web-runtime/tests/unit/pages/__snapshots__/resolvePublicLink.spec.ts.snap
  tests/e2e/support/api/graph/userManagement.ts
Labels: Type:Enhancement
