Repository opencloud-eu/web, pull requests merged in 2025-10, with the labels that each got.

#1294 fix: topbar save icon hover color and thumbnail compression
  packages/web-pkg/src/components/AppTopBar.vue
  packages/web-pkg/src/components/FilesList/ResourceListItem.vue
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
  packages/web-pkg/tests/unit/components/__snapshots__/AppTopBar.spec.ts.snap
Labels: Type:Bug

#1298 fix: user group assignment options, details panel alignment
  packages/web-app-admin-settings/src/components/Users/AddToGroupsModal.vue
  packages/web-app-admin-settings/src/components/Users/RemoveFromGroupsModal.vue
  packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
  packages/web-app-admin-settings/src/composables/actions/users/useUserActionsRemoveFromGroups.ts
  packages/web-app-admin-settings/tests/unit/components/Users/AddToGroupsModal.spec.ts
  packages/web-app-admin-settings/tests/unit/components/Users/RemoveFromGroupsModal.spec.ts
  packages/web-app-admin-settings/tests/unit/components/Users/SideBar/DetailsPanel.spec.ts
  packages/web-app-admin-settings/tests/unit/composables/actions/users/useUserActionsRemoveFromGroups.spec.ts
Labels: Type:Bug

#1300 fix: clean failed uploads when closing upload overlay
  packages/web-pkg/src/services/uppy/uppyService.ts
  packages/web-runtime/src/components/UploadInfo.vue
  packages/web-runtime/tests/unit/components/UploadInfo.spec.ts
  web.d.ts
Labels: Type:Bug

#1306 feat: set view mode e.G tiles or table view globally, add condensed view to Spaces view
  packages/web-app-files/src/composables/extensions/useFolderViews.ts
  packages/web-app-files/src/composables/resourcesViewDefaults/useResourcesViewDefaults.ts
  packages/web-app-files/src/views/spaces/Projects.vue
  packages/web-app-files/tests/unit/views/spaces/Projects.spec.ts
  packages/web-pkg/src/components/ViewOptions.vue
Labels: Type:Enhancement

#1296 fix: resolve axe violations (button-name, empty-table-header, spinner)
  packages/design-system/src/components/OcAvatars/OcAvatars.vue
  packages/design-system/src/components/OcAvatars/__snapshots__/OcAvatars.spec.ts.snap
  packages/design-system/src/components/OcBreadcrumb/OcBreadcrumb.vue
  packages/design-system/src/components/OcBreadcrumb/__snapshots__/OcBreadcrumb.spec.ts.snap
  packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
  packages/design-system/src/components/OcSpinner/OcSpinner.vue
  packages/web-app-admin-settings/src/components/Groups/GroupsList.vue
  packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
  packages/web-app-admin-settings/src/components/Users/UsersList.vue
  packages/web-app-admin-settings/src/views/Users.vue
  packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
  packages/web-app-external/tests/unit/__snapshots__/app.spec.ts.snap
  packages/web-app-files/src/components/Shares/SharedWithMeSection.vue
  packages/web-app-files/tests/unit/components/SideBar/__snapshots__/ActivitiesPanel.spec.ts.snap
  packages/web-pkg/src/components/ContextActions/ActionMenuItem.vue
  packages/web-pkg/src/components/CreateLinkModal.vue
  packages/web-pkg/src/components/FilesList/ResourceLink.vue
  packages/web-pkg/src/components/FilesList/ResourceListItem.vue
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/tests/unit/components/AppTemplates/__snapshots__/LoadingScreen.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ActionMenuDropItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextActionMenu.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap
Labels: Type:Bug

#1319 fail accessibility tests on any violation
  .woodpecker.env
  .woodpecker.star
  docker-compose.yml
  tests/e2e/support/utils/accessibility.ts
Labels: Type:Test

#1323 feat: add update check for mobile view
  packages/web-app-admin-settings/src/views/Users.vue
  packages/web-pkg/src/components/FilesList/ResourceLink.vue
  packages/web-pkg/src/components/FilesList/ResourceListItem.vue
  packages/web-pkg/src/composables/piniaStores/index.ts
  packages/web-pkg/src/composables/piniaStores/updates.ts
  packages/web-pkg/src/types.ts
  packages/web-runtime/src/components/MobileNav.vue
  packages/web-runtime/src/components/VersionCheck.vue
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/index.ts
  packages/web-runtime/tests/unit/components/VersionCheck.spec.ts
  packages/web-test-helpers/src/mocks/pinia.ts
Labels: Type:Enhancement

#1277 fix: prevent uploading the same file again during upload
  packages/web-app-files/src/HandleUpload.ts
  packages/web-pkg/src/services/uppy/uppyService.ts
  packages/web-runtime/src/components/UploadInfo.vue
Labels: Type:Bug

#1327 fix: normalize file and folder names to NFC when uploading
  packages/web-pkg/src/services/uppy/uppyService.ts
Labels: Type:Bug

#1332 fix: disable echart loading in text editor
  packages/web-pkg/src/components/TextEditor/TextEditor.vue
Labels: Type:Bug

#1310 feat: tiles view for trash
  packages/web-app-files/src/composables/extensions/useFolderViews.ts
  packages/web-app-files/src/extensionPoints.ts
  packages/web-app-files/src/views/spaces/GenericTrash.vue
  packages/web-app-files/src/views/trash/Overview.vue
  packages/web-app-files/tests/unit/views/spaces/GenericTrash.spec.ts
  packages/web-app-files/tests/unit/views/trash/Overview.spec.ts
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-pkg/src/components/FilesList/ResourceTile.vue
  packages/web-pkg/src/components/FilesList/ResourceTiles.vue
  packages/web-pkg/tests/unit/components/FilesList/ResourceTile.spec.ts
  packages/web-pkg/tests/unit/components/FilesList/ResourceTiles.spec.ts
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTile.spec.ts.snap
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/trashbin/actions.ts
Labels: Type:Enhancement
