Repository opencloud-eu/web, pull requests merged in 2025-04, with the labels that each got.

#465 fix: archive download with archives >2GB
  packages/web-pkg/src/services/archiver.ts
Labels: Type:Bug

#469 fix: hide request-id when it's undefined
  packages/web-pkg/src/composables/piniaStores/messages.ts
Labels: Type:Bug

#467 fix: archive download with archives >2GB
  packages/web-pkg/src/services/archiver.ts
Labels: Type:Bug

#472 feat: make meta data panels more appealing
  packages/web-app-files/src/components/SideBar/Audio/AudioMetaPanel.vue
  packages/web-app-files/src/components/SideBar/Details/FileDetails.vue
  packages/web-app-files/src/components/SideBar/Exif/ExifPanel.vue
Labels: Type:Enhancement

#477 chore(deps): bump @babel/runtime to v7.27.0
  pnpm-lock.yaml
Labels: Type:Dependencies

#479 style: only add underline to oc table thead when table cell is sortable
  packages/design-system/src/components/OcTable/OcTable.vue
Labels: Type:Design

#480 fix: spaces overview item count
  packages/web-app-files/src/views/spaces/Projects.vue
Labels: Type:Bug

#482 fix: remove zoom indicator to avoid confusion
  packages/web-app-preview/src/components/MediaControls.vue
  packages/web-app-preview/tests/unit/components/MediaControls.spec.ts
Labels: Type:Bug

#481 fix(files): truncation on long link names
  packages/web-app-files/src/components/SideBar/Shares/Links/ListItem.vue
Labels: Type:Bug

#486 [full-ci]use Playwright api instead of node fetch
  tests/e2e/cucumber/environment/index.ts
  tests/e2e/support/api/davSpaces/spaces.ts
  tests/e2e/support/api/graph/spaces.ts
  tests/e2e/support/api/graph/userManagement.ts
  tests/e2e/support/api/http.ts
  tests/e2e/support/api/keycloak/openCloudUserToken.ts
  tests/e2e/support/api/keycloak/user.ts
  tests/e2e/support/api/keycloak/utils.ts
  tests/e2e/support/api/share/share.ts
  tests/e2e/support/api/token/utils.ts
Labels: Type:Test

#494 Revert "Disable the 'exclude' patterns on the path conditional for now"
  .woodpecker.star
Labels: Type:DevOps

#493 fix(design-system): design system live doc blocks
  packages/design-system/CNAME
  packages/design-system/docs/.vitepress/components/LiveCodeBlock.vue
  packages/design-system/docs/.vitepress/theme/index.ts
  packages/design-system/index.html
  packages/design-system/package.json
  pnpm-lock.yaml
Labels: Type:Bug

#500 chore: bump version to v2.2.0
  package.json
  packages/design-system/package.json
  packages/eslint-config/package.json
  packages/extension-sdk/package.json
  packages/prettier-config/package.json
  packages/tsconfig/package.json
  packages/web-client/package.json
  packages/web-pkg/package.json
  packages/web-test-helpers/package.json
Labels: Type:Maintenance

#484 purge cache after every CI run
  .woodpecker.star
Labels: Type:DevOps

#501 chore: remove web tag from tag create/push-script
  dev/scripts/create_and_push_tags.sh
Labels: Type:Maintenance

#505 test for #453
  tests/e2e/cucumber/features/navigation/personalSpacePagination.feature
  tests/e2e/cucumber/features/spaces/pagination.feature
  tests/e2e/cucumber/features/user-settings/languageChange.feature
  tests/e2e/cucumber/features/user-settings/pagination.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: Type:Test

#510 [full-ci] remove unneeded variables
  .woodpecker.star
Labels: Type:DevOps

#512 feat: adjust sidebar preview in the spaces view, so they look equal as the tiles
  packages/web-pkg/src/components/SideBar/Spaces/Details/SpaceDetails.vue
Labels: Type:Feature

#514 remove unneeded parentheses
  .woodpecker.star
Labels: Type:DevOps

#515 [full-ci] opencloud bump
  .woodpecker.env
Labels: Type:DevOps

#489 fix(files): truncation on long link names
  packages/web-app-files/src/components/SideBar/Shares/Links/ListItem.vue
Labels: Type:Bug

#518 delete unneeded containers and directories
  .woodpecker.star
Labels: Type:DevOps

#520 fix: use native fetch for downloading archives
  packages/web-pkg/src/services/archiver.ts
  packages/web-pkg/src/services/client/client.ts
  packages/web-pkg/tests/unit/services/archiver.spec.ts
Labels: Type:Bug

#523 chore: remove dev docs, since added to opencloud-eu/opencloud repo
  docs/_index.md
  docs/backend-opencloud.md
  docs/building.md
  docs/deployments/_index.md
  docs/development/_index.md
  docs/development/conventions.md
  docs/development/repo-structure.md
  docs/development/tooling.md
  docs/embed-mode/_index.md
  docs/extension-system/_index.md
  docs/extension-system/extension-types/_index.md
  docs/extension-system/extension-types/actions.md
  docs/extension-system/extension-types/app-menu-items.md
  docs/extension-system/extension-types/custom-components.md
  docs/extension-system/extension-types/folder-view.md
  docs/extension-system/extension-types/left-sidebar-menu-item.md
  docs/extension-system/extension-types/right-sidebar-panels.md
  docs/extension-system/extension-types/search.md
  docs/extension-system/viewer-editor-apps.md
  docs/getting-started.md
  docs/releasing.md
  docs/testing/_index.md
  docs/testing/e2e-testing-standards.md
  docs/testing/testing.md
  docs/theming/_index.md
Labels: Type:Documentation

#527 ci: enable ready-release-go for stable-2.1
  .woodpecker.star
Labels: Type:DevOps

#534 ci: do not overwrite release when uploading artifacts
  .woodpecker.star
Labels: Type:DevOps

#532 download big archive
  .woodpecker.env
  tests/e2e/cucumber/features/app-provider/secureView.feature
  tests/e2e/cucumber/features/file-action/download.feature
  tests/e2e/cucumber/features/navigation/shortcut.feature
  tests/e2e/cucumber/features/ocm/ocm.feature
  tests/e2e/cucumber/features/search/fullTextSearch.feature
  tests/e2e/cucumber/features/search/search.feature
  tests/e2e/cucumber/features/shares/link.feature
  tests/e2e/cucumber/features/smoke/activity.feature
  tests/e2e/cucumber/features/user-settings/languageChange.feature
  tests/e2e/cucumber/steps/api.ts
  tests/e2e/cucumber/steps/ui/adminSettings.ts
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: Type:Test

#533 [full-ci] Remove code duplication in CI
  .woodpecker.star
Labels: Type:DevOps

#536 fix: reintroduce ct helper read more links
  packages/web-app-files/src/helpers/contextualHelpers.ts
  packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
Labels: Type:Bug, Type:Documentation

#538 docs: fix 404 links in readme
  README.md
Labels: Type:Documentation

#541 chore: fix pnpm check:all command
  package.json
Labels: Type:DevOps

#549 fix: added padding to readonly-text-editor
  packages/web-app-text-editor/src/App.vue
Labels: Type:Bug

#550 fix: added avatar styling and truncated user name to avoid compressed…
  packages/design-system/src/components/OcAvatar/OcAvatar.vue
  packages/web-app-admin-settings/src/components/Groups/SideBar/MembersRoleSection.vue
Labels: Type:Bug

#551 fix: removed unnecessary oc-text-truncate to avoid a cut off
  packages/web-app-admin-settings/src/components/Groups/SideBar/MembersPanel.vue
  packages/web-app-admin-settings/tests/unit/components/Groups/SideBar/__snapshots__/MembersPanel.spec.ts.snap
Labels: Type:Bug

#537 ci: make release plugin compatible with stable branch workflow
  release-config.ts
Labels: Type:DevOps

#554 ci: add workflow for design-system docs
  .woodpecker.star
  Makefile
  packages/design-system/docs/.vitepress/components/ComponentApi.vue
  packages/design-system/docs/.vitepress/config.ts
Labels: Type:DevOps

#565 [full-ci] bump opencloud stable
  .woodpecker.env
Labels: Type:Maintenance

#556 ci: make release plugin compatible with stable branch workflow
  release-config.ts
Labels: Type:DevOps

#586 fix: remove outline on markdown editor and make input and preview are…
  packages/design-system/src/styles/theme/helper.scss
  packages/web-pkg/src/components/TextEditor/TextEditor.vue
Labels: Type:Bug

#559 chore: remove old and unused stuff
  .depcheckrc
  .gitignore
  .renovaterc.json
  .woodpecker.star
  changelog/CHANGELOG-Release.tmpl
  changelog/CHANGELOG.tmpl
  changelog/README.md
  changelog/TEMPLATE
  changelog/changelog-csv.tmpl
  changelog/unreleased/.keep
  config/config.json.sample-opencloud
  package.json
  packages/design-system/.depcheckrc
  patches/jest-serializer-vue-tjw@3.19.0.patch
  patches/v-calendar@2.3.4.patch
  pnpm-lock.yaml
Labels: Type:Maintenance

#601 chore: bump version to v2.3.0
  package.json
  packages/design-system/package.json
  packages/eslint-config/package.json
  packages/extension-sdk/package.json
  packages/prettier-config/package.json
  packages/tsconfig/package.json
  packages/web-client/package.json
  packages/web-pkg/package.json
  packages/web-test-helpers/package.json
Labels: Type:Maintenance

#607 fix: show remaining quota as unrestricted if quota is unrestricted
  packages/web-app-admin-settings/src/components/Spaces/SpacesList.vue
  packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
  packages/web-app-files/src/views/spaces/Projects.vue
Labels: Type:Bug

#578 fix: chrome oh snap errors
  packages/web-app-files/src/components/SideBar/ActivitiesPanel.vue
  packages/web-app-files/tests/unit/components/SideBar/ActivitiesPanel.spec.ts
  packages/web-pkg/src/components/SideBar/SideBar.vue
Labels: Type:Bug

#612 PR label checker
  .github/workflows/labels.yml
Labels: Type:Maintenance

#610 feat: allow delete file within app
  packages/web-app-preview/src/App.vue
  packages/web-pkg/src/components/AppTemplates/AppWrapper.vue
  packages/web-pkg/src/composables/actions/files/useFileActionsDelete.ts
  packages/web-pkg/src/composables/actions/helpers/index.ts
  packages/web-pkg/src/composables/actions/helpers/useFileActionsDeleteResources.ts
  packages/web-pkg/src/composables/actions/helpers/useIsAppActive.ts
  packages/web-pkg/tests/unit/composables/actions/helpers/useFileActionsDeleteResources.spec.ts
  tests/e2e/cucumber/features/file-action/delete.feature
  tests/e2e/cucumber/steps/ui/resources.ts
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/index.ts
Labels: Type:Feature

#611 chore(design-system): bundle css & externalize vue
  packages/design-system/README.md
  packages/design-system/package.json
  packages/design-system/src/index.ts
  packages/design-system/vite.config.ts
Labels: Type:Maintenance
