Repository opencloud-eu/web, pull requests merged in 2025-09, with the labels that each got.

#1121 feat: hide Login allowed for users
  packages/web-app-admin-settings/src/components/Users/SideBar/DetailsPanel.vue
  packages/web-app-admin-settings/src/components/Users/SideBar/EditPanel.vue
  packages/web-app-admin-settings/src/components/Users/UsersList.vue
  packages/web-app-admin-settings/src/views/Users.vue
  packages/web-client/src/ocs/capabilities.ts
  packages/web-pkg/src/composables/piniaStores/capabilities.ts
Labels: Type:Feature

#1132 fix(design-system): docs after tailwind migration
  packages/design-system/docs/.vitepress/components/LiveCodeBlock.vue
  packages/design-system/docs/.vitepress/config.ts
  packages/design-system/docs/.vitepress/theme/custom.scss
  packages/design-system/docs/.vitepress/theme/index.ts
  packages/design-system/docs/.vitepress/theme/tailwind.css
  packages/design-system/docs/components/OcRecipient/OcRecipient.md
  packages/design-system/package.json
  packages/design-system/src/styles/tailwind.css
  pnpm-lock.yaml
Labels: Type:Bug

#1137 [full-ci] bump-opencloud-3.4.0. run all tests
  .woodpecker.env
Labels: Type:Dependencies

#1145 feat: enable feedback link and fix button color
  packages/web-pkg/src/composables/piniaStores/config/config.ts
  packages/web-runtime/src/components/Topbar/FeedbackLink.vue
Labels: Type:Enhancement

#1138 refactor: css mixins and custom-classes to tailwind
  packages/design-system/src/components/OcBottomDrawer/__snapshots__/OcBottomDrawer.spec.ts.snap
  packages/design-system/src/components/OcButton/OcButton.spec.ts
  packages/design-system/src/components/OcButton/OcButton.vue
  packages/design-system/src/components/OcCheckbox/OcCheckbox.spec.ts
  packages/design-system/src/components/OcCheckbox/OcCheckbox.vue
  packages/design-system/src/components/OcDrop/OcDrop.spec.ts
  packages/design-system/src/components/OcDrop/OcDrop.vue
  packages/design-system/src/components/OcIcon/OcIcon.vue
  packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
  packages/design-system/src/components/OcRadio/OcRadio.spec.ts
  packages/design-system/src/components/OcRadio/OcRadio.vue
  packages/design-system/src/components/OcSpinner/OcSpinner.vue
  packages/design-system/src/components/OcTable/OcTable.vue
  packages/design-system/src/components/OcTag/OcTag.vue
  packages/design-system/src/components/OcTag/__snapshots__/OcTag.spec.ts.snap
  packages/design-system/src/components/OcTextInput/__snapshots__/OcTextInput.spec.ts.snap
  packages/design-system/src/helpers/index.ts
  packages/design-system/src/helpers/sizeClasses.ts
  packages/design-system/src/helpers/tailwind.ts
  packages/design-system/src/helpers/types.ts
  packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
  packages/web-app-epub-reader/tests/unit/__snapshots__/app.spec.ts.snap
  packages/web-app-files/src/components/AppBar/CreateAndUpload.vue
  packages/web-app-files/tests/unit/components/AppBar/Upload/__snapshots__/ResourceUpload.spec.ts.snap
  packages/web-app-files/tests/unit/components/AppBar/__snapshots__/CreateAndUpload.spec.ts.snap
  packages/web-app-files/tests/unit/components/Shares/__snapshots__/CopyPrivateLink.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/Shares/Collaborators/InviteCollaborator/__snapshots__/RecipientContainer.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/Shares/Links/__snapshots__/CopyLink.spec.ts.snap
  packages/web-app-files/tests/unit/components/SideBar/Shares/__snapshots__/FileShares.spec.ts.snap
  packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-pkg/src/components/ContextActions/ContextActionMenu.vue
  packages/web-pkg/src/components/CreateLinkModal.vue
  packages/web-pkg/tests/unit/components/AppBar/__snapshots__/CreateSpace.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ActionMenuDropItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextActionMenu.spec.ts.snap
  packages/web-pkg/tests/unit/components/ContextActions/__snapshots__/ContextMenuQuickAction.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTiles.spec.ts.snap
  packages/web-pkg/tests/unit/components/Filters/__snapshots__/DateFilter.spec.ts.snap
  packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNavItem.spec.ts.snap
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/NotificationBell.spec.ts.snap
  packages/web-runtime/tests/unit/components/Topbar/__snapshots__/SidebarToggle.spec.ts.snap
  packages/web-runtime/tests/unit/pages/__snapshots__/accessDenied.spec.ts.snap
  packages/web-runtime/tests/unit/pages/__snapshots__/account.spec.ts.snap
Labels: Type:Maintenance

#1144 fix: remove flaky resourceExists
  tests/e2e/cucumber/features/journeys/kindergarten.feature
  tests/e2e/cucumber/features/navigation/breadcrumb.feature
  tests/e2e/cucumber/features/oidc/refreshToken.feature
  tests/e2e/cucumber/features/search/search.feature
  tests/e2e/cucumber/features/shares/link.feature
  tests/e2e/cucumber/features/smoke/trashbinDelete.feature
  tests/e2e/cucumber/features/smoke/upload.feature
  tests/e2e/cucumber/features/spaces/project.feature
  tests/e2e/support/objects/app-files/resource/actions.ts
  tests/e2e/support/objects/app-files/resource/utils.ts
Labels: Type:Test

#1148 refactor: migrate grid to tailwind
  packages/web-app-files/src/components/FilesViewWrapper.vue
  packages/web-app-files/src/components/SideBar/Audio/AudioMetaPanel.vue
  packages/web-app-files/src/components/SideBar/Shares/Collaborators/EditDropdown.vue
  packages/web-app-files/src/components/SideBar/Shares/FileLinks.vue
  packages/web-pkg/src/components/AppTopBar.vue
  packages/web-pkg/src/components/FilesList/ResourceTiles.vue
  packages/web-pkg/src/components/SearchBarFilter.vue
  packages/web-pkg/src/components/SideBar/Spaces/SpaceInfo.vue
  packages/web-pkg/tests/unit/components/__snapshots__/AppTopBar.spec.ts.snap
  packages/web-runtime/src/components/Topbar/TopBar.vue
Labels: Type:Enhancement

#1157 feat: add view mode switch to mobile view
  packages/web-app-files/src/composables/extensions/useFolderViews.ts
  packages/web-pkg/src/components/ViewOptions.vue
Labels: Type:Feature

#1156 refactor: migrate z-index to tailwind
  packages/design-system/src/components/OcAvatars/OcAvatars.vue
  packages/design-system/src/components/OcBottomDrawer/OcBottomDrawer.spec.ts
  packages/design-system/src/components/OcBottomDrawer/OcBottomDrawer.vue
  packages/design-system/src/components/OcBottomDrawer/__snapshots__/OcBottomDrawer.spec.ts.snap
  packages/design-system/src/components/OcFilterChip/OcFilterChip.vue
  packages/design-system/src/components/OcList/OcList.vue
  packages/design-system/src/components/OcModal/OcModal.vue
  packages/design-system/src/components/OcModal/__snapshots__/OcModal.spec.ts.snap
  packages/design-system/src/components/OcNotifications/OcNotifications.vue
  packages/design-system/src/components/OcSearchBar/OcSearchBar.vue
  packages/design-system/src/components/OcTable/OcTable.vue
  packages/design-system/src/styles/tailwind.css
  packages/web-app-admin-settings/src/components/AppTemplate.vue
  packages/web-app-admin-settings/tests/unit/components/Spaces/__snapshots__/SpacesList.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/views/__snapshots__/Spaces.spec.ts.snap
  packages/web-app-admin-settings/tests/unit/views/__snapshots__/Users.spec.ts.snap
  packages/web-app-app-store/src/components/AppImageGallery.vue
  packages/web-app-files/src/App.vue
  packages/web-app-files/src/components/EmbedActions/EmbedActions.vue
  packages/web-app-files/src/components/FilesViewWrapper.vue
  packages/web-app-files/src/views/FilesDrop.vue
  packages/web-app-files/tests/unit/views/spaces/__snapshots__/Projects.spec.ts.snap
  packages/web-app-files/tests/unit/views/trash/__snapshots__/Overview.spec.ts.snap
  packages/web-app-preview/src/components/MediaControls.vue
  packages/web-app-search/src/portals/SearchBar.vue
  packages/web-pkg/src/components/AppBar/AppBar.vue
  packages/web-pkg/src/components/FilesList/ResourceGhostElement.vue
  packages/web-pkg/src/components/FilesList/ResourceTile.vue
  packages/web-pkg/src/components/SearchBarFilter.vue
  packages/web-pkg/src/components/SideBar/FileSideBar.vue
  packages/web-pkg/tests/unit/components/AppBar/__snapshots__/AppBar.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceTile.spec.ts.snap
  packages/web-pkg/tests/unit/components/Filters/__snapshots__/DateFilter.spec.ts.snap
  packages/web-pkg/tests/unit/components/__snapshots__/ItemFilter.spec.ts.snap
  packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
  packages/web-runtime/src/components/SkipTo.vue
  packages/web-runtime/src/components/Topbar/Notifications.vue
  packages/web-runtime/src/components/Topbar/TopBar.vue
  packages/web-runtime/src/layouts/Application.vue
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap
Labels: Type:Enhancement

#1166 fix: shortcut links not opening in tiles view
  packages/web-pkg/src/components/FilesList/ResourceListItem.vue
  packages/web-pkg/src/components/FilesList/ResourceTile.vue
Labels: Type:Bug

#1173 fix mobile flaky test
  tests/e2e/support/objects/app-files/resource/actions.ts
Labels: Type:Test

#1186 e2e-tests. remove create odt file from mobile suite
  .woodpecker.star
  tests/e2e/cucumber/features/mobile-view/smoke.feature
Labels: Type:Test

#1187 fix: check byte length on name validation instead of character count
  packages/web-pkg/src/composables/actions/helpers/useIsResourceNameValid.ts
  packages/web-pkg/src/constants.ts
  packages/web-pkg/src/helpers/index.ts
  packages/web-pkg/src/helpers/textByteSize.ts
  packages/web-pkg/tests/unit/composables/actions/helpers/useIsResourceNameValid.spec.ts
Labels: Type:Bug

#1212 fix flaky. sharing test
  tests/e2e/support/objects/app-files/utils/sidebar.ts
Labels: Type:Test

#1209 fix: line-height of resource name
  packages/web-pkg/src/components/FilesList/ResourceName.vue
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceListItem.spec.ts.snap
  packages/web-pkg/tests/unit/components/FilesList/__snapshots__/ResourceName.spec.ts.snap
Labels: Type:Bug

#1219 feat: remove edit space description inline button
  packages/web-app-files/src/components/Spaces/SpaceHeader.vue
  packages/web-app-files/tests/unit/components/Spaces/__snapshots__/SpaceHeader.spec.ts.snap
Labels: Type:Enhancement

#1233 fix: authenticated requests in password protected public links
  packages/web-pkg/src/composables/authContext/useRequest.ts
  packages/web-pkg/src/services/client/auth.ts
Labels: Type:Bug

#1235 feat: add dark mode for OcDatePicker
  packages/design-system/src/components/OcDatepicker/OcDatepicker.spec.ts
  packages/design-system/src/components/OcDatepicker/OcDatepicker.vue
  packages/web-pkg/src/components/CreateLinkModal.vue
  packages/web-pkg/src/components/Filters/DateFilter.vue
  packages/web-pkg/src/components/Modals/DatePickerModal.vue
  packages/web-runtime/src/components/Modals/AppTokenModal.vue
  packages/web-runtime/tests/unit/components/Modals/AppTokenModal.spec.ts
Labels: Type:Enhancement

#1241 feat: add more screen real estate for images in preview app
  packages/web-app-preview/src/components/Sources/MediaImage.vue
Labels: Type:Enhancement

#1256 feat(extension-sdk): add tailwind vite plugin to vite config
  packages/design-system/docs/gettingStarted/installation.md
  packages/design-system/docs/gettingStarted/tailwindMigration.md
  packages/design-system/vite.config.ts
  packages/extension-sdk/index.mjs
  packages/extension-sdk/package.json
  pnpm-lock.yaml
Labels: Type:Enhancement

#1257 chore(extension-sdk): bump to v4.1.0-alpha.1
  packages/extension-sdk/package.json
Labels: Type:Maintenance

#1266 fix: add missing web-pkg types and fix type errors
  packages/design-system/src/components/OcAvatars/OcAvatars.vue
  packages/design-system/src/components/OcTable/OcTable.vue
  packages/web-pkg/src/components/FilesList/ResourceTable.vue
  packages/web-pkg/tsconfig.json
  packages/web-pkg/vite.config.ts
Labels: Type:Bug

#1249 feat: load config authenticated
  packages/web-pkg/src/apps/types.ts
  packages/web-pkg/src/composables/piniaStores/apps.ts
  packages/web-runtime/src/components/Topbar/TopBar.vue
  packages/web-runtime/src/container/bootstrap.ts
  packages/web-runtime/src/index.ts
  packages/web-runtime/src/layouts/Application.vue
  packages/web-runtime/tests/unit/components/Topbar/TopBar.spec.ts
Labels: Type:Enhancement

#1264 feat: add update check
  dev/docker/opencloud/csp.yaml
  packages/web-app-admin-settings/src/components/General/InfoSection.vue
  packages/web-client/src/ocs/capabilities.ts
  packages/web-runtime/src/components/SidebarNav/SidebarNav.vue
  packages/web-runtime/src/components/VersionCheck.vue
  packages/web-runtime/tests/unit/components/SidebarNav/SidebarNav.spec.ts
  packages/web-runtime/tests/unit/components/SidebarNav/__snapshots__/SidebarNav.spec.ts.snap
  packages/web-runtime/tests/unit/components/VersionCheck.spec.ts
Labels: Type:Feature

#1272 feat: account page enhancements: remove last table row border, adjust…
  packages/web-runtime/src/components/Account/AccountTable.vue
  packages/web-runtime/src/pages/account/accountInformation.vue
  packages/web-runtime/tests/unit/pages/account/__snapshots__/accountInformation.spec.ts.snap
Labels: Type:Enhancement

#1267 [full-ci][tests-only] Increase playwright timeout
  tests/e2e/config.js
Labels: Type:Test

#1274 fix: sync color role defaults with opencloud theme.json
  packages/design-system/src/styles/defaults.css
Labels: Type:Bug, Type:Documentation

#1289 chore(extension-sdk): bump to v4.1.0-alpha.2
  packages/extension-sdk/package.json
Labels: Type:Maintenance
